using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Jeevika.StaticFiles
{
    public class Application_csproj
    {
        public static void WriteContent(StreamWriter f, Application application)
        {
            f.WriteLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>", "");
            f.WriteLine("<Project ToolsVersion=\"15.0\" DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">", "");
            f.WriteLine("  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\TypeScript\\Microsoft.TypeScript.Default.props\" Condition=\"Exists('$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\TypeScript\\Microsoft.TypeScript.Default.props')\" />", "");
            f.WriteLine("  <Import Project=\"..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\\build\\net46\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props\" Condition=\"Exists('..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\\build\\net46\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')\" />", "");
            f.WriteLine("  <Import Project=\"$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props\" Condition=\"Exists('$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props')\" />", "");
            f.WriteLine("  <PropertyGroup>", "");
            f.WriteLine("    <Configuration Condition=\" '$(Configuration)' == '' \">Debug</Configuration>", "");
            f.WriteLine("    <Platform Condition=\" '$(Platform)' == '' \">AnyCPU</Platform>", "");
            f.WriteLine("    <ProductVersion>", "");
            f.WriteLine("    </ProductVersion>", "");
            f.WriteLine("    <SchemaVersion>2.0</SchemaVersion>", "");
            f.WriteLine("    <ProjectGuid>{{7C488288-A112-4E17-9C82-0E263A6F7B85}}</ProjectGuid>", "");
            f.WriteLine("    <ProjectTypeGuids>{{349c5851-65df-11da-9384-00065b846f21}};{{fae04ec0-301f-11d3-bf4b-00c04f79efbc}}</ProjectTypeGuids>", "");
            f.WriteLine("    <OutputType>Library</OutputType>", "");
            f.WriteLine("    <AppDesignerFolder>Properties</AppDesignerFolder>", "");
            f.WriteLine("    <RootNamespace>{0}</RootNamespace>", "");
            f.WriteLine("    <AssemblyName>{0}</AssemblyName>", "");
            f.WriteLine("    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>", "");
            f.WriteLine("    <MvcBuildViews>false</MvcBuildViews>", "");
            f.WriteLine("    <UseIISExpress>true</UseIISExpress>", "");
            f.WriteLine("    <Use64BitIISExpress />", "");
            f.WriteLine("    <IISExpressSSLPort>44321</IISExpressSSLPort>", "");
            f.WriteLine("    <IISExpressAnonymousAuthentication />", "");
            f.WriteLine("    <IISExpressWindowsAuthentication />", "");
            f.WriteLine("    <IISExpressUseClassicPipelineMode />", "");
            f.WriteLine("    <UseGlobalApplicationHostFile />", "");
            f.WriteLine("    <NuGetPackageImportStamp>", "");
            f.WriteLine("    </NuGetPackageImportStamp>", "");
            f.WriteLine("    <TypeScriptToolsVersion>3.4</TypeScriptToolsVersion>", "");
            f.WriteLine("  </PropertyGroup>", "");
            f.WriteLine("  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \">", "");
            f.WriteLine("    <DebugSymbols>true</DebugSymbols>", "");
            f.WriteLine("    <DebugType>full</DebugType>", "");
            f.WriteLine("    <Optimize>false</Optimize>", "");
            f.WriteLine("    <OutputPath>bin\\</OutputPath>", "");
            f.WriteLine("    <DefineConstants>DEBUG;TRACE</DefineConstants>", "");
            f.WriteLine("    <ErrorReport>prompt</ErrorReport>", "");
            f.WriteLine("    <WarningLevel>4</WarningLevel>", "");
            f.WriteLine("  </PropertyGroup>", "");
            f.WriteLine("  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' \">", "");
            f.WriteLine("    <DebugSymbols>true</DebugSymbols>", "");
            f.WriteLine("    <DebugType>pdbonly</DebugType>", "");
            f.WriteLine("    <Optimize>true</Optimize>", "");
            f.WriteLine("    <OutputPath>bin\\</OutputPath>", "");
            f.WriteLine("    <DefineConstants>TRACE</DefineConstants>", "");
            f.WriteLine("    <ErrorReport>prompt</ErrorReport>", "");
            f.WriteLine("    <WarningLevel>4</WarningLevel>", "");
            f.WriteLine("  </PropertyGroup>", "");
            f.WriteLine("  <ItemGroup>", "");
            f.WriteLine("    <Reference Include=\"Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\\lib\\net45\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"Microsoft.CSharp\" />", "");
            f.WriteLine("    <Reference Include=\"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <HintPath>..\\packages\\Newtonsoft.Json.12.0.2\\lib\\net45\\Newtonsoft.Json.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System\" />", "");
            f.WriteLine("    <Reference Include=\"System.Data\" />", "");
            f.WriteLine("    <Reference Include=\"System.Drawing\" />", "");
            f.WriteLine("    <Reference Include=\"System.Web.DynamicData\" />", "");
            f.WriteLine("    <Reference Include=\"System.Web.Entity\" />", "");
            f.WriteLine("    <Reference Include=\"System.Web.ApplicationServices\" />", "");
            f.WriteLine("    <Reference Include=\"System.ComponentModel.DataAnnotations\" />", "");
            f.WriteLine("    <Reference Include=\"System.Core\" />", "");
            f.WriteLine("    <Reference Include=\"System.Data.DataSetExtensions\" />", "");
            f.WriteLine("    <Reference Include=\"System.Xml.Linq\" />", "");
            f.WriteLine("    <Reference Include=\"System.Web\" />", "");
            f.WriteLine("    <Reference Include=\"System.Web.Extensions\" />", "");
            f.WriteLine("    <Reference Include=\"System.Web.Abstractions\" />", "");
            f.WriteLine("    <Reference Include=\"System.Web.Routing\" />", "");
            f.WriteLine("    <Reference Include=\"System.Xml\" />", "");
            f.WriteLine("    <Reference Include=\"System.Configuration\" />", "");
            f.WriteLine("    <Reference Include=\"System.Web.Services\" />", "");
            f.WriteLine("    <Reference Include=\"System.EnterpriseServices\" />", "");
            f.WriteLine("    <Reference Include=\"Microsoft.Web.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.Web.Infrastructure.1.0.0.0\\lib\\net40\\Microsoft.Web.Infrastructure.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Net.Http\">", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Net.Http.WebRequest\">", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Web.Helpers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.AspNet.WebPages.3.2.7\\lib\\net45\\System.Web.Helpers.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.AspNet.Mvc.5.2.7\\lib\\net45\\System.Web.Mvc.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Web.Optimization\">", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.AspNet.Web.Optimization.1.1.3\\lib\\net40\\System.Web.Optimization.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Web.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.AspNet.Razor.3.2.7\\lib\\net45\\System.Web.Razor.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Web.WebPages, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.AspNet.WebPages.3.2.7\\lib\\net45\\System.Web.WebPages.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Web.WebPages.Deployment, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.AspNet.WebPages.3.2.7\\lib\\net45\\System.Web.WebPages.Deployment.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\Microsoft.AspNet.WebPages.3.2.7\\lib\\net45\\System.Web.WebPages.Razor.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"WebGrease\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\WebGrease.1.6.0\\lib\\WebGrease.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("    <Reference Include=\"Antlr3.Runtime\">", "");
            f.WriteLine("      <Private>True</Private>", "");
            f.WriteLine("      <HintPath>..\\packages\\Antlr.3.5.0.2\\lib\\Antlr3.Runtime.dll</HintPath>", "");
            f.WriteLine("    </Reference>", "");
            f.WriteLine("  </ItemGroup>", "");
            f.WriteLine("  <ItemGroup>", "");
            f.WriteLine("    <Compile Include=\"App_Start\\BundleConfig.cs\" />", "");
            f.WriteLine("    <Compile Include=\"App_Start\\FilterConfig.cs\" />", "");
            f.WriteLine("    <Compile Include=\"App_Start\\RouteConfig.cs\" />", "");
            f.WriteLine("    <Compile Include=\"Controllers\\HomeController.cs\" />", "");
            f.WriteLine("    <Compile Include=\"Converters\\DateTimeConverter.cs\" />", "");
            f.WriteLine("    <Compile Include=\"Global.asax.cs\">", "");
            f.WriteLine("      <DependentUpon>Global.asax</DependentUpon>", "");
            f.WriteLine("    </Compile>", "");
            f.WriteLine("    <Compile Include=\"Properties\\AssemblyInfo.cs\" />", "");
            f.WriteLine("  </ItemGroup>", "");
            f.WriteLine("  <ItemGroup>", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap-grid.css\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap-grid.min.css\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap-reboot.css\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap-reboot.min.css\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap.css\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap.min.css\" />", "");
            f.WriteLine("    <Content Include=\"favicon.ico\" />", "");
            f.WriteLine("    <Content Include=\"Global.asax\" />", "");
            f.WriteLine("    <Content Include=\"Content\\Site.css\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\bootstrap.bundle.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\bootstrap.bundle.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\bootstrap.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\bootstrap.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\bootstrap.min.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\bootstrap.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\bootstrap.bundle.min.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\bootstrap.bundle.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap.min.css.map\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap.css.map\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap-reboot.min.css.map\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap-reboot.css.map\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap-grid.min.css.map\" />", "");
            f.WriteLine("    <Content Include=\"Content\\bootstrap-grid.css.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\esm\\popper-utils.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\esm\\popper-utils.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\esm\\popper.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\esm\\popper.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\esm\\popper.min.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\esm\\popper.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\esm\\popper-utils.min.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\esm\\popper-utils.js.map\" />", "");
            f.WriteLine("    <None Include=\"Scripts\\jquery-3.4.1.intellisense.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery-3.4.1.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery-3.4.1.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery-3.4.1.slim.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery-3.4.1.slim.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery-3.4.1.slim.min.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery-3.4.1.min.map\" />", "");
            f.WriteLine("    <None Include=\"Scripts\\jquery.validate-vsdoc.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery.validate.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery.validate.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery.validate.unobtrusive.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\jquery.validate.unobtrusive.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\modernizr-2.8.3.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\popper-utils.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\popper-utils.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\popper.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\popper.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\umd\\popper-utils.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\umd\\popper-utils.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\umd\\popper.js\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\umd\\popper.min.js\" />", "");
            f.WriteLine("    <Content Include=\"Web.config\" />", "");
            f.WriteLine("    <Content Include=\"Web.Debug.config\">", "");
            f.WriteLine("      <DependentUpon>Web.config</DependentUpon>", "");
            f.WriteLine("    </Content>", "");
            f.WriteLine("    <Content Include=\"Web.Release.config\">", "");
            f.WriteLine("      <DependentUpon>Web.config</DependentUpon>", "");
            f.WriteLine("    </Content>", "");
            f.WriteLine("    <Content Include=\"Views\\Web.config\" />", "");
            f.WriteLine("    <Content Include=\"Views\\_ViewStart.cshtml\" />", "");
            f.WriteLine("    <Content Include=\"Views\\Shared\\Error.cshtml\" />", "");
            f.WriteLine("    <Content Include=\"Views\\Shared\\_Layout.cshtml\" />", "");
            f.WriteLine("    <Content Include=\"Views\\Home\\Index.cshtml\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\umd\\popper.min.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\umd\\popper.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\umd\\popper-utils.min.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\umd\\popper-utils.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\README.md\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\popper.min.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\popper.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\popper-utils.min.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Scripts\\popper-utils.js.map\" />", "");
            f.WriteLine("    <Content Include=\"Images\\android-chrome-192x192.png\" />", "");
            f.WriteLine("    <Content Include=\"Images\\android-chrome-512x512.png\" />", "");
            f.WriteLine("    <Content Include=\"Images\\apple-touch-icon.png\" />", "");
            f.WriteLine("    <Content Include=\"Images\\favicon.ico\" />", "");
            f.WriteLine("    <Content Include=\"Images\\favicon-16x16.png\" />", "");
            f.WriteLine("    <Content Include=\"Images\\favicon-32x32.png\" />", "");
            f.WriteLine("  </ItemGroup>", "");
            f.WriteLine("  <ItemGroup>", "");
            f.WriteLine("    <Folder Include=\"App_Data\\\" />", "");
            f.WriteLine("    <Folder Include=\"Models\\\" />", "");
            f.WriteLine("  </ItemGroup>", "");
            f.WriteLine("  <ItemGroup>", "");
            f.WriteLine("    <None Include=\"packages.config\" />", "");
            f.WriteLine("  </ItemGroup>", "");
            f.WriteLine("  <ItemGroup>", "");
            f.WriteLine("    <Service Include=\"{{4A0DDDB5-7A95-4FBF-97CC-616D07737A77}}\" />", "");
            f.WriteLine("  </ItemGroup>", "");
            f.WriteLine("  <ItemGroup>", "");
            f.WriteLine("    <TypeScriptCompile Include=\"Scripts\\index.d.ts\" />", "");
            f.WriteLine("  </ItemGroup>", "");
            f.WriteLine("  <PropertyGroup>", "");
            f.WriteLine("    <VisualStudioVersion Condition=\"'$(VisualStudioVersion)' == ''\">10.0</VisualStudioVersion>", "");
            f.WriteLine("    <VSToolsPath Condition=\"'$(VSToolsPath)' == ''\">$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)</VSToolsPath>", "");
            f.WriteLine("  </PropertyGroup>", "");
            f.WriteLine("  <Import Project=\"$(MSBuildBinPath)\\Microsoft.CSharp.targets\" />", "");
            f.WriteLine("  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\TypeScript\\Microsoft.TypeScript.targets\" Condition=\"Exists('$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\TypeScript\\Microsoft.TypeScript.targets')\" />", "");
            f.WriteLine("  <Import Project=\"$(VSToolsPath)\\WebApplications\\Microsoft.WebApplication.targets\" Condition=\"'$(VSToolsPath)' != ''\" />", "");
            f.WriteLine("  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v10.0\\WebApplications\\Microsoft.WebApplication.targets\" Condition=\"false\" />", "");
            f.WriteLine("  <Target Name=\"MvcBuildViews\" AfterTargets=\"AfterBuild\" Condition=\"'$(MvcBuildViews)'=='true'\">", "");
            f.WriteLine("    <AspNetCompiler VirtualPath=\"temp\" PhysicalPath=\"$(WebProjectOutputDir)\" />", "");
            f.WriteLine("  </Target>", "");
            f.WriteLine("  <ProjectExtensions>", "");
            f.WriteLine("    <VisualStudio>", "");
            f.WriteLine("      <FlavorProperties GUID=\"{{349c5851-65df-11da-9384-00065b846f21}}\">", "");
            f.WriteLine("        <WebProjectProperties>", "");
            f.WriteLine("          <UseIIS>True</UseIIS>", "");
            f.WriteLine("          <AutoAssignPort>True</AutoAssignPort>", "");
            f.WriteLine("          <DevelopmentServerPort>26894</DevelopmentServerPort>", "");
            f.WriteLine("          <DevelopmentServerVPath>/</DevelopmentServerVPath>", "");
            f.WriteLine("          <IISUrl>https://localhost:44321/</IISUrl>", "");
            f.WriteLine("          <NTLMAuthentication>False</NTLMAuthentication>", "");
            f.WriteLine("          <UseCustomServer>False</UseCustomServer>", "");
            f.WriteLine("          <CustomServerUrl>", "");
            f.WriteLine("          </CustomServerUrl>", "");
            f.WriteLine("          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>", "");
            f.WriteLine("        </WebProjectProperties>", "");
            f.WriteLine("      </FlavorProperties>", "");
            f.WriteLine("    </VisualStudio>", "");
            f.WriteLine("  </ProjectExtensions>", "");
            f.WriteLine("  <Target Name=\"EnsureNuGetPackageBuildImports\" BeforeTargets=\"PrepareForBuild\">", "");
            f.WriteLine("    <PropertyGroup>", "");
            f.WriteLine("      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {{0}}.</ErrorText>", "");
            f.WriteLine("    </PropertyGroup>", "");
            f.WriteLine("    <Error Condition=\"!Exists('..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\\build\\net46\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')\" Text=\"$([System.String]::Format('$(ErrorText)', '..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\\build\\net46\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props'))\" />", "");
            f.WriteLine("  </Target>", "");
            f.WriteLine("  <Target Name=\"CopyRoslynFiles\" AfterTargets=\"AfterBuild\" Condition=\"!$(Disable_CopyWebApplication) And '$(OutDir)' != '$(OutputPath)'\">", "");
            f.WriteLine("    <ItemGroup>", "");
            f.WriteLine("      <RoslynFiles Include=\"$(CscToolPath)\\*\" />", "");
            f.WriteLine("    </ItemGroup>", "");
            f.WriteLine("    <MakeDir Directories=\"$(WebProjectOutputDir)\\bin\\roslyn\" />", "");
            f.WriteLine("    <Copy SourceFiles=\"@(RoslynFiles)\" DestinationFolder=\"$(WebProjectOutputDir)\\bin\\roslyn\" SkipUnchangedFiles=\"true\" Retries=\"$(CopyRetryCount)\" RetryDelayMilliseconds=\"$(CopyRetryDelayMilliseconds)\" />", "");
            f.WriteLine("  </Target>", "");
            f.WriteLine("</Project>", "");
        }
    }
}
